baseURL = "https://rangerblo.ga"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "Ranger 的博客"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="/img/CCBYNCSA.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
# copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-183804296-3"

disqusShortname = "RangerNJU"

enableRobotsTXT = true

hasCJKLanguage = true

# Paginate = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#ccc"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  backgroundDark = "black"
  backgroundImageDark = "/me/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  images = ["me/background.jpg"]

  author = "Ranger"
  description = "Ranger 的生活记录～"
  avatar = "/me/avatar.png"
  headerTitle = "Ranger 的博客"
  motto = "在滚滚浊世 绝不把梦交出"
  categoriesLimitInHeader = 3
  # headerBottomText = ""

  rss = true

  # utterancesRepo = "RangerNJU/RangerNJU.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = "ck1RbGO7MF7X7NESN0VuQXfI-gzGzoHsz"
  # LEANCLOUD_APP_KEY = "mhNrrlkWjqT5rY3YD7gknUNy"
  
  email = "ranger.nju@gmail.com"
  #twitter = "g1eny0ung"
  #facebook = "g1eny0ung"
  #instagram = "g1eny0ung"
  # mastodon = ""
  #linkedin = "g1eny0ung"
  github = "rangerNJU"
  bilibili = "28597465"
  #stackoverflow = "5676489/g1eny0ung"
  #codepen = "g1eny0ung"

  siteStartYear = 2020

  favicon = "/favicon.png"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
